{{- if .Values.image.pullSecret }}
apiVersion: v1
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.image.pullSecret.server }}": {
          "username": "{{ .Values.image.pullSecret.username }}",
          "password": "{{ .Values.image.pullSecret.password }}",
          "auth": {{ printf "%s:%s" .Values.image.pullSecret.username .Values.image.pullSecret.password | b64enc | quote }}
        }
      }
    }
kind: Secret
metadata:
  name: {{ include "guardllama.fullname" . }}-imagepullsecret
type: kubernetes.io/dockerconfigjson
{{- end }}

---

{{- if .Values.tunnelImage.pullSecret }}
apiVersion: v1
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.tunnelImage.pullSecret.server }}": {
          "username": "{{ .Values.tunnelImage.pullSecret.username }}",
          "password": "{{ .Values.tunnelImage.pullSecret.password }}",
          "auth": {{ printf "%s:%s" .Values.tunnelImage.pullSecret.username .Values.tunnelImage.pullSecret.password | b64enc | quote }}
        }
      }
    }
kind: Secret
metadata:
  name: {{ include "guardllama.fullname" . }}-tunnel-imagepullsecret
type: kubernetes.io/dockerconfigjson
{{- end }}


---

apiVersion: v1
stringData:
  signKey: |
    {{ .Values.jwt.signKey | nindent 4 }}
  verifyKey: |
    {{ .Values.jwt.verifyKey | nindent 4 }}
kind: Secret
metadata:
  name: {{ include "guardllama.fullname" . }}-jwtkey
type: Opaque
